export const charAbilityScoreInitialState = {
  str: 10,
  dex: 10,
  con: 10,
  int: 10,
  wis: 10,
  cha: 10,
  strMod: 0,
  dexMod: 0,
  conMod: 0,
  intMod: 0,
  wisMod: 0,
  chaMod: 0,
};

export const alignments = {
  LG: "Lawful Good",
  LN: "Lawful Neutral",
  LE: "Lawful Evil",
  NG: "Neutral Good",
  N: "True Neutral",
  NE: "Neutral Evil",
  CG: "Chaotic Good",
  CN: "Chaotic Neutral",
  CE: "Chaotic Evil",
};

export const charHeaderInitialState = {
  name: "",
  alignment: "LG",
  player: "",
  campaign: "",
  class: "",
  level: 1,
  race: "",
  deity: "",
  homeland: "",
  size: "",
  gender: "",
  age: "",
  height: 0,
  metricHeight: 0,
  weight: 0,
  metricWeight: 0,
  hair: "",
  eyes: "",
};

export const healthInitialState = {
  hpCurrent: 0,
  hpMax: 0,
  wounds: 0,
  woundsNonLethal: 0,
  initiative: 0,
  DR: 0,
  SR: 0,
  drBypass: "",
};

export const charDefenses = {
  ac: 0,
  abilityMod: 0,
  armorBonus: 0,
  shieldBonus: 0,
  sizeMod: 0,
  natArmor: 0,
  deflectMod: 0,
  miscMod: 0,
};

export const drBypassTypes = [
  "--",
  "Magic",
  "Cold Iron",
  "Bludgeoning",
  "Piercing",
  "Slashing",
  "Epic",
  "Adamantine",
  "Silver",
  "Good",
  "Evil",
  "Chaos",
  "Law",
];

export const skills = {
  acrobactics: {
    abilityBonus: 0,
    abilityMod: "dex",
    armorCheckPenalty: true,
    classSkill: false,
    description: "You can keep your balance while traversing narrow or treacherous surfaces",
    miscMod: 0,
    ranks: 0,
    skillname: "acrobatics",
    skillTotal: 0,
    trainedOnly: false,
  },
  appraise: {
    abilityBonus: 0,
    abilityMod: "int",
    armorCheckPenalty: false,
    classSkill: false,
    description: "You can evaluate the monetary value of an object",
    miscMod: 0,
    ranks: 0,
    skillname: "appraise",
    skillTotal: 0,
    trainedOnly: false,
  },
  bluff: {
    abilityBonus: 0,
    abilityMod: "cha",
    armorCheckPenalty: false,
    classSkill: false,
    description: "You know how to tell a lie",
    miscMod: 0,
    ranks: 0,
    skillname: "bluff",
    skillTotal: 0,
    trainedOnly: false,
  },
  climb: {
    abilityBonus: 0,
    abilityMod: "str",
    armorCheckPenalty: true,
    classSkill: false,
    description: "You are skilled scaling vertical surfaces, from smooth city walls to rocky cliffs",
    miscMod: 0,
    ranks: 0,
    skillname: "climb",
    skillTotal: 0,
    trainedOnly: false,
  },
  craft: {
    abilityBonus: 0,
    abilityMod: "int",
    armorCheckPenalty: false,
    classSkill: false,
    craftSkillGroup: "",
    description: "You are skilled in the creation of a specific group of items, such as armor or weapons",
    miscMod: 0,
    ranks: 0,
    skillname: "craft",
    skillTotal: 0,
    trainedOnly: false,
  },
  craft2: {
    abilityBonus: 0,
    abilityMod: "int",
    armorCheckPenalty: false,
    classSkill: false,
    craftSkillGroup: "",
    description: "You are skilled in the creation of a specific group of items, such as armor or weapons",
    miscMod: 0,
    ranks: 0,
    skillname: "craft",
    skillTotal: 0,
    trainedOnly: false,
  },
  diplomacy: {
    abilityBonus: 0,
    abilityMod: "cha",
    armorCheckPenalty: false,
    classSkill: false,
    description: "You can use this skill to persuade others to agree with your arguments, to resolve differences, and to gather valuable information or rumors from people.",
    miscMod: 0,
    ranks: 0,
    skillname: "diplomacy",
    skillTotal: 0,
    trainedOnly: false,
  },
  disableDevice: {
    abilityBonus: 0,
    abilityMod: "dex",
    armorCheckPenalty: true,
    classSkill: false,
    description: "You are skilled at disarming traps and opening locks.",
    miscMod: 0,
    ranks: 0,
    skillname: "disable device",
    skillTotal: 0,
    trainedOnly: true,
  },
  disguise: {
    abilityBonus: 0,
    abilityMod: "cha",
    armorCheckPenalty: false,
    classSkill: false,
    description: "You are skilled at changing your appearance.",
    miscMod: 0,
    ranks: 0,
    skillname: "disguise",
    skillTotal: 0,
    trainedOnly: false,
  },
  escapeArtist: {
    abilityBonus: 0,
    abilityMod: "dex",
    armorCheckPenalty: true,
    classSkill: false,
    description: "You training allows you to slip out of bonds and escape from grapples.",
    miscMod: 0,
    ranks: 0,
    skillname: "escape artist",
    skillTotal: 0,
    trainedOnly: false,
  },
  fly: {
    abilityBonus: 0,
    abilityMod: "dex",
    armorCheckPenalty: true,
    classSkill: false,
    description: "You are skilled at flying, through either the use of wings or magic, and can perform daring or complex maneuvers while airborne.",
    miscMod: 0,
    ranks: 0,
    skillname: "fly",
    skillTotal: 0,
    trainedOnly: false,
  },
  handleAnimal: {
    abilityBonus: 0,
    abilityMod: "cha",
    armorCheckPenalty: false,
    classSkill: false,
    description: "You are trained at working with animals, and can teach them tricks, get them to follow your simples commands, or even domesticate them.",
    miscMod: 0,
    ranks: 0,
    skillname: "handle animal",
    skillTotal: 0,
    trainedOnly: true,
  },
};

